[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002360AB167D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/381f5c20-d656-495d-a6d8-2654ea356851/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002360AB17590>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/381f5c20-d656-495d-a6d8-2654ea356851/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002360AB35890>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/381f5c20-d656-495d-a6d8-2654ea356851/url