{"name": "test_checkout", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'CredKart_Checkout' has no attribute 'Success_Message1_XPATH'", "trace": "self = <testCases.test_CheckOut.Test_CredKart_CheckOut object at 0x00000281FFBB0B10>\nsetup = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"8f5e70b4-faba-46d4-8ce2-0a9a07c717f1\")>\n\n    def test_checkout(self,setup):\n        self.driver = setup\n        self.lp = Login(self.driver)\n        self.driver.get(\"https://automation.credence.in/login\")\n        self.lp.Enter_Email(\"Credenceppb3@test.com\")\n        self.lp.Enter_Password(\"Credence@123\")\n        self.lp.Click_Login_Button()\n        self.cop = CredKart_Checkout(self.driver)\n        self.cop.click_macbook()\n        self.cop.click_addtocart()\n        self.cop.click_proceedtocheckout()\n        self.cop.enter_firstname(\"Panchashil\")\n        self.cop.enter_lastname(\"Birajdar\")\n        self.cop.enter_phone(\"9456787878\")\n        self.cop.enter_address(\"Lakshmi Kunj, Narayan Nagar, Latur\")\n        self.cop.enter_zip(\"413512\")\n        self.cop.dropdown_state(\"Pune\")\n        self.cop.enter_ownername(\"Panchashil Birajdar\")\n        self.cop.enter_cvv(\"043\")\n        self.cop.enter_cardnumber(\"5281\")\n        self.cop.enter_cardnumber(\"0370\")\n        self.cop.enter_cardnumber(\"4891\")\n        self.cop.enter_cardnumber(\"6168\")\n        self.cop.dropdown_year(\"2025\")\n        self.cop.dropdown_month(\"May\")\n        self.cop.click_checkout()\n>       print(\"Order number is =\", str(self.cop.dis_successmessage()))\n\ntestCases\\test_CheckOut.py:39: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pageObjects.CheckOutPage.CredKart_Checkout object at 0x00000281FFB98490>\n\n    def dis_successmessage(self):\n>       self.driver.find_element(*CredKart_Checkout.Success_Message1_XPATH).text()\nE       AttributeError: type object 'CredKart_Checkout' has no attribute 'Success_Message1_XPATH'\n\npageObjects\\CheckOutPage.py:79: AttributeError"}, "start": 1709734867824, "stop": 1709734879150, "uuid": "8f6039c2-8045-4f0b-9e15-5126d4dee7ce", "historyId": "20cc9b2348db3bab61b49695b043e22b", "testCaseId": "20cc9b2348db3bab61b49695b043e22b", "fullName": "testCases.test_CheckOut.Test_CredKart_CheckOut#test_checkout", "labels": [{"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_CheckOut"}, {"name": "subSuite", "value": "Test_CredKart_CheckOut"}, {"name": "host", "value": "DESKTOP-OJCC0SH"}, {"name": "thread", "value": "9396-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_CheckOut"}]}